<a href="https://colab.research.google.com/github/ggj0228/practicePyton/blob/main/numpyBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 모듈과 패키지

In [54]:
# 모듈은 변수 함수 클래스를 담고 있는 파일 (.py)
# 패키지는 그런 모듈을 묶음 단순하게 폴더
# import 모듈
# import 모듈1, 모듈2
# 모듈.변수
# 모듈.함수
# 모듈.클래스


In [55]:
import math # math라는 모듈
print(math.pi)
print(math.sqrt(4))

3.141592653589793
2.0


In [56]:
import math as m

print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [57]:
from math import pi,sqrt
print(pi)
print(sqrt(4))



3.141592653589793
2.0


In [58]:
from math import *

print(pi)
print(sqrt(4))
print(sin(pi))

3.141592653589793
2.0
1.2246467991473532e-16


In [59]:
from math import sqrt as s, pi as p

print(s(4))
print(p)

2.0
3.141592653589793


In [60]:
# import 패키지
# import 패키지.모듈
# import 패키지.모듈1, 패키지.모듈2

# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [61]:
import numpy as np # numpy는 라이브러리 (패키지와 모듈들을 모아놓음)다 numerical python

a = np.array([1,2,3])

print(a)
type(np.array)

[1 2 3]


builtin_function_or_method

In [62]:
import numpy.random

print(numpy.random.randn(3,3)) # Normal distribution (3,3)은 3행 3열 짜리를 의미

[[ 0.93553003  0.26220592  1.44588201]
 [-0.76692235  0.1625122   0.5575523 ]
 [-0.56787267  0.69455194  0.20634203]]


In [63]:
import numpy.random as nr

print(nr.randn(3,3))



[[ 1.45575044  1.47829078 -0.55220169]
 [ 1.63755694  1.33115194 -0.03318827]
 [-0.7056007  -0.52997443 -1.08399626]]


In [64]:
from numpy.random import randn
print(randn(3,3))

[[-0.30220596  0.00923626 -0.22849173]
 [ 0.1607176   0.48845652 -0.28925943]
 [-0.7157279  -0.26577628  0.69320985]]


In [65]:
from numpy.random import *

print(randn(3,3))
print(rand(3,3)) # uniform distribution

[[-1.09267206  0.88391285 -0.88018443]
 [ 0.03541157  1.2338332   0.34827955]
 [-0.48638383 -0.16329659 -0.56696198]]
[[0.02403297 0.2883847  0.61732287]
 [0.10924537 0.37222153 0.50135404]
 [0.18713962 0.40957402 0.70793144]]


In [66]:
from numpy.random import randn as rn

print(rn(3,3))

[[-0.41850482  1.00107236  1.55373469]
 [ 0.16350112  1.59305618  0.50489489]
 [-0.68515062  2.03525783 -0.14045949]]


In [67]:
from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))


[[ 0.09029593  1.48415886 -0.70272627]
 [-0.90436303  1.78135391  0.35997556]
 [ 0.28504955  1.85477179 -0.07526592]]
[[0.35099588 0.60825941 0.58976201]
 [0.97106673 0.82786954 0.11404239]
 [0.83252886 0.94661604 0.1861177 ]]


## numpy 본격적으로

In [68]:
import numpy as np
a = np.array([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)

b = np.array([1,2,  3.1, 4])
print(b.dtype)
print(type(b[0])) # 하나라도 실수면 자동으로 실수 타입을

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64
<class 'numpy.float64'>


In [69]:
A = np.array([[1,2], [3,4]]) # 이 셀부터는 import numpy as np 실행했다 치고 작성
# A = np.array([1,2], [3,4,5])  # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.size) # 전체 성분의
# A.size = A.shape[0] * A.shape[1]

[[1 2]
 [3 4]]
(2, 2)
2
4


In [70]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros((3,3))) # 튜플을 입력으로! 그냥 np.zeros(3,3)은 안 돼요
print(np.arange(3,10,2)) # range랑 같은데 array로 만들어줌
print(np.arange(0,1,0.1)) # 소수점 가능
print(np.linspace(0,1,10, endpoint=False)) # 0에서부터 1포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [71]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
print(c) # 드디어! 양옆으로 길어지는 게 아닌 벡터의 합이 나옴!


[5 7 9]


In [72]:
a = np.array([[1,2,3], [1,2,3]])
b = np.array([[4,5,6], [1,1,1]])
c = a + b
print(c)
d = a - b
print(d)
print(a * b) # 곱셈은 성분끼리의 곱! (Hadamard product)
print(a / b) # 나누기도 마찬가지
print(b**2) # 제곱도 각 성분에 대해서 해준다

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]
[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


In [73]:
a = np.array([[1,2], [3,4]])
b = np.array([[1,2], [3,4]])
print(a * b)
print(a @ b)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


## numpy의 인덱싱과 슬라이싱


In [74]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[:7])

1
2
9
[2 3 4]
[1 2 3 4 5 6 7]


In [75]:
# 행렬에 대한 인덱싱과 슬라이싱
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A[0])
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # numpy에서만 가능
B = [[1,2,3,4],[5,6,7,8]]
print(B[0][2])
# print(B[0,2]) # error!
print(A[1,:]) # 1행, 전부
print(A[1,0:3:2])
print(A[:2]) # 전부 2열

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
3
[4 5 6]
[4 6]
[[1 2 3]
 [4 5 6]]


In [89]:
# boolean 인덱싱
a= [1,2,3,4,5,3,3]
print(a==3) # 여러개 값들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A = np.array([[1,2,3,4], [5,3,7,3]])
print(A==3) # 리스트와 달리 각 요소에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!

A[A==3] = 100
print(A) # 그러면 이러한 것도 가능하다( 3과 같은 애를 100으로 바꿔줘)

A = np.array([[1,2],[3,4], [5,6], [7,8]])
B = np.array([True, False, False, True]) # 참고로 그냥 리스트여도 됨
A[B, :] # 0행 3행 슬라이싱


b = np.array([1,2,3,4])
print(b)
print(b[[True, False, False,True]])
c=[1,2,3,4]
# c[[True, False, False, True]] #error!



False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2 100   4]
 [  5 100   7 100]]
[1 2 3 4]
[1 4]


In [91]:
# 3차원 행렬 인덱싱
A = np.array([ [[0,1,2,3], [4,5,6,7], [8,9,10,11]],
              [[12,13,14,15], [16,17,18,19], [20,21,22,23]]])

print(A)
print(A.shape) # 대괄호가 하나 늘어나면 왼쪽 shape값이 추가 된다.
print(A[0,1,2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6


## numpy 여러 함수들

In [102]:
A = np.random.randn(3,3) # 여긴 튜플로 안줘도 됨
B = np.random.rand(3,3)
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0번째 열이 음수인 행들

[[-0.00532595 -0.81125894  1.69138526]
 [-1.12906752  1.17167284 -1.43037901]
 [-0.15604615  0.36619918 -0.76029046]]
[[0.96714305 0.81715747 0.31316873]
 [0.09390978 0.98093689 0.56204971]
 [0.45294478 0.91103629 0.18027373]]
[[-0.00532595 -0.81125894  1.69138526]
 [-1.12906752  1.17167284 -1.43037901]
 [-0.15604615  0.36619918 -0.76029046]]


In [114]:
A = np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1)))
print(np.log2(2))
print(np.log10(10))
print(np.round) # 반올림
print(np.round(A,2)) # 소수점 둘째자리까지
print(np.floor(A)) # 내림
print(np.ceil(A)) # 올림

[[-1.68656876  0.74891144 -2.70342712]
 [ 0.36876387 -0.52920686 -0.78738519]
 [ 0.74378456  2.40465511 -3.15455185]]
[[1.68656876 0.74891144 2.70342712]
 [0.36876387 0.52920686 0.78738519]
 [0.74378456 2.40465511 3.15455185]]
[[1.29867962 0.8653967  1.64421018]
 [0.60725931 0.72746606 0.88734728]
 [0.86242945 1.55069504 1.77610581]]
[[ 0.18515374  2.11469679  0.06697559]
 [ 1.44594613  0.589072    0.45503307]
 [ 2.10388275 11.07461011  0.04265751]]
[[ 0.52269614 -0.28913454  0.99452027]
 [-0.99759875 -0.63637588 -0.23903771]
 [-0.29600385  0.87740649  1.14884644]]
1.0
1.0
1.0
<function round at 0x7d1eac533600>
[[-1.69  0.75 -2.7 ]
 [ 0.37 -0.53 -0.79]
 [ 0.74  2.4  -3.15]]
[[-2.  0. -3.]
 [ 0. -1. -1.]
 [ 0.  2. -4.]]
[[-1.  1. -2.]
 [ 1. -0. -0.]
 [ 1.  3. -3.]]


In [120]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/6))
print(np.tan(np.pi/6))
print(np.tanh(-10))

0.49999999999999994
0.8660254037844387
0.5773502691896257
-0.9999999958776927


In [125]:
# np.nan # not a number
# np.log(-1)
print(np.isnan([1,2,np.nan,3,4]))
print(np.isinf([1,2,np.nan,3,np.inf]))

[False False  True False False]
[False False False False  True]


In [137]:
A = np.random.randn(3,4)
print(A)
print(np.max(A))
print(np.max(A, axis = 0))
print(np.max(A, axis = 1))
print(np.max(A, axis = 0, keepdims=True))
print(np.max(A, axis = 1, keepdims=True))
print(np.min(A))
print(np.min(A, axis = 0))
print(np.argmax(A))
print(np.argmax(A, axis = 0)) # 각 열에서에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A, axis = 1)) # 각 행에서 가장 큰 애가 존재하는 인덱스


[[ 0.61646592  1.23065186 -0.71297632  0.39564422]
 [-0.52550076  1.41930931  0.20475379  1.35583788]
 [ 0.43314685 -2.31757552  0.53122977  1.75358191]]
1.7535819059237356
[0.61646592 1.41930931 0.53122977 1.75358191]
[1.23065186 1.41930931 1.75358191]
[[0.61646592 1.41930931 0.53122977 1.75358191]]
[[1.23065186]
 [1.41930931]
 [1.75358191]]
-2.31757552018659
[-0.52550076 -2.31757552 -0.71297632  0.39564422]
11
[0 1 2 2]
[1 1 3]


In [141]:
a=np.random.randn(6,1)
print(a)
a_sorted=np.sort(a,axis=0)
print(a_sorted)
print(np.flipud(a_sorted))

[[-0.47663399]
 [ 0.19632208]
 [-0.98876342]
 [ 0.74377119]
 [-0.72169771]
 [ 0.01472904]]
[[-0.98876342]
 [-0.72169771]
 [-0.47663399]
 [ 0.01472904]
 [ 0.19632208]
 [ 0.74377119]]
[[ 0.74377119]
 [ 0.19632208]
 [ 0.01472904]
 [-0.47663399]
 [-0.72169771]
 [-0.98876342]]


In [142]:
A = np.random.randn(3,4)
print(A)
print(np.sum(A))
print(np.sum(A, axis = 1))
print(np.sum(A, axis = 1 ,keepdims = True)) # 3행 1열짜리 2D array

print(np.mean(A))
print(np.mean(A, axis = 1))
print(np.mean(A, axis = 1, keepdims = True))

print(np.std(A)) # standard deviation 표준 편차


[[-0.82716438 -1.52761356 -1.28109684  0.33383553]
 [-0.54891031  1.10537541  0.62757532 -1.11331866]
 [ 0.04388959 -0.40808198 -0.33572871 -1.45639019]]
-5.387628784168374
[-3.30203925  0.07072176 -2.15631129]
[[-3.30203925]
 [ 0.07072176]
 [-2.15631129]]
-0.4489690653473645
[-0.82550981  0.01768044 -0.53907782]
[[-0.82550981]
 [ 0.01768044]
 [-0.53907782]]
0.811906737989913


In [152]:
A = np.random.randint(1,5, size=(3,4))
print(A)
print(A.shape)
B = A.reshape(2,2,3)
print(B)
print(B.ndim) # 3차원 행렬이다

[[2 3 4 4]
 [4 2 1 2]
 [1 1 1 1]]
(3, 4)
[[[2 3 4]
  [4 4 2]]

 [[1 2 1]
  [1 1 1]]]
3


In [161]:
a=np.array([1,2,3])
b=np.array([2,2,1])
print(a@b)
print(np.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose()@b)
print(a.T@b)

A = np.random.randn(4,3,2)
print(A.transpose(0,2,1).shape)

9
9
[[9]]
[[9]]
(4, 2, 3)


In [169]:
A = np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape)  # 4개 행이 될 수 있도록 열의 수를 맞춰라(-1)
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(2, 2, 5)
(1, 20)
(20, 1)


In [176]:
x = np.random.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1,2,...] 는 x[1,2,:,:,:] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape)
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape)

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
(3, 4, 6)
(3, 4, 6)


In [183]:
A=np.ones((2,2))
B=np.zeros((2,2,))

print(A)
print(B)

C = np.hstack([A,B])
print(C)

D = np.vstack([A,B])
print(D)

E = np.block([A,B])
F = np.block([[A], [B]])
print(E)
print(F)

G = np.block([[[A]], [[B]]])
print(G)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]


In [188]:
A = np.random.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(axis=(0,1,4,5)).shape)

(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [195]:
A = np.random.randn(3,4)
A1 = A[np.newaxis,:,:] # np.newaxis is None <- True
print(A1.shape)
A2 = A[...,np.newaxis]
print(A2.shape)
A3 = A[:, np.newaxis, :]
print(A3.shape)
A1 = np.expand_dims(A,axis=0)
print(A1.shape)
A2 = np.expand_dims(A,axis=2)
print(A2.shape)
A3 = np.expand_dims(A,axis=1)
print(A3.shape)
A1 = A.reshape(1,3,4)
print(A1.shape)
A2 = A.reshape(3,4,1)
print(A2.shape)
A3 = A.reshape(4,3,1)
print(A3.shape)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(4, 3, 1)
